### ISSUE TITLE
当配置canal.async=false报错

### ISSUE THREAD

**Issue by javaXN** [behappy-project/behappy-canal#2]
Parameter 0 of method simpleCanalClient in org.xiaowu.behappy.canal.client.spring.boot.autoconfigure.SimpleClientAutoConfiguration required a bean of type 'org.xiaowu.behappy.canal.client.handler.MessageHandler' that could not be found.

**Comment by wang-xiaowu** [comment]
请耐心等待下，这似乎是因为spring6的一个bug引起的

详见:  https://github.com/spring-projects/spring-framework/issues/30688

**Comment by wang-xiaowu** [comment]
请更新至3.0.3版本
